import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:cloud_firestore/cloud_firestore.dart' hide Transaction;
import '../../../models/transaction.dart';
import '../../../core/services/firebase_providers.dart';

class TransactionRepository {
  final FirebaseFirestore _firestore;

  TransactionRepository(this._firestore);

  // Add Transaction
  Future<void> addTransaction(Transaction transaction) async {
    final data = transaction.toJson();
    // Remove fields that are autogenerated or looked up
    data.remove('id');
    data.remove('created_by_name'); 
    data['created_at'] = FieldValue.serverTimestamp();
    
    await _firestore.collection('transactions').add(data);
  }

  // Get Transactions with pagination and filtering
  Future<List<Transaction>> getTransactions({
    required String userId,
    required bool isAdmin,
    int? limit,
    int? offset,
    String? typeFilter,
    DateTime? startDate,
    DateTime? endDate,
  }) async {
    Query<Map<String, dynamic>> query = _firestore.collection('transactions');

    if (!isAdmin) {
      query = query.where('created_by', isEqualTo: userId);
    }

    if (typeFilter != null) {
      query = query.where('type', isEqualTo: typeFilter);
    }

    if (startDate != null) {
      query = query.where('created_at', isGreaterThanOrEqualTo: Timestamp.fromDate(startDate));
    }
    if (endDate != null) {
      query = query.where('created_at', isLessThanOrEqualTo: Timestamp.fromDate(endDate));
    }

    // query = query.orderBy('created_at', descending: true); // Removed to avoid index requirement

    final snapshot = await query.get();

    final docs = snapshot.docs;
    List<QueryDocumentSnapshot<Map<String, dynamic>>> filteredDocs = docs;

    if (offset != null || limit != null) {
      // Note: This paging might be inaccurate because we haven't sorted yet.
      // But for small datasets we'll sort the final resultList.
    }

    List<Transaction> resultList = [];
    Map<String, String> profileNames = {};

    for (var doc in filteredDocs) {
      final json = doc.data();
      json['id'] = doc.id;
      
      if (json['created_at'] is Timestamp) {
        json['created_at'] = (json['created_at'] as Timestamp).toDate().toIso8601String();
      } else if (json['created_at'] == null) {
        json['created_at'] = DateTime.now().toIso8601String();
      }

      final createdBy = json['created_by'] as String?;
      
      String? fullName;
      if (createdBy != null && isAdmin) {
         if (!profileNames.containsKey(createdBy)) {
            final profileDoc = await _firestore.collection('profiles').doc(createdBy).get();
            if (profileDoc.exists) {
               final profileData = profileDoc.data();
               profileNames[createdBy] = (profileData?['full_name'] as String?) ?? (profileData?['email'] as String?) ?? 'Bilinmeyen';
            } else {
               profileNames[createdBy] = 'Bilinmeyen';
            }
         }
         fullName = profileNames[createdBy];
         json['profiles'] = {'full_name': fullName, 'email': ''};
      }

      resultList.add(Transaction.fromJson(json));
    }

    // Local sort at the end
    resultList.sort((a, b) => b.createdAt.compareTo(a.createdAt));
    return resultList;
  }

  // Get Balance (Admin only)
  Future<Map<String, double>> getBalance() async {
    final snapshot = await _firestore.collection('transactions').get();

    double totalIncome = 0;
    double totalExpense = 0;
    double cashIncome = 0, cardIncome = 0, checkIncome = 0;
    double cashExpense = 0, cardExpense = 0, checkExpense = 0;

    for (var doc in snapshot.docs) {
      final item = doc.data();
      final type = item['type'] as String;
      final method = item['payment_method'] as String? ?? 'cash';
      final amount = (item['amount'] as num).toDouble();

      if (type == 'income') {
        totalIncome += amount;
        switch (method) {
          case 'cash': cashIncome += amount; break;
          case 'credit_card': cardIncome += amount; break;
          case 'check_note': checkIncome += amount; break;
        }
      } else if (type == 'expense') {
        totalExpense += amount;
        switch (method) {
          case 'cash': cashExpense += amount; break;
          case 'credit_card': cardExpense += amount; break;
          case 'check_note': checkExpense += amount; break;
        }
      }
    }

    return {
      'total_income': totalIncome,
      'total_expense': totalExpense,
      'net_balance': totalIncome - totalExpense,
      'cash_income': cashIncome,
      'card_income': cardIncome,
      'check_income': checkIncome,
      'cash_expense': cashExpense,
      'card_expense': cardExpense,
      'check_expense': checkExpense,
    };
  }

  // Update Transaction
  Future<void> updateTransaction(String id, Transaction transaction) async {
    final data = transaction.toJson();
    data.remove('id');
    data.remove('created_at'); 
    data.remove('created_by_name');
    
    try {
      await _firestore.collection('transactions').doc(id).update(data);
    } catch(e) {
      throw Exception('Güncelleme gerçekleştirilemedi. $e');
    }
  }

  // Delete Transaction
  Future<void> deleteTransaction(String id) async {
    try {
      await _firestore.collection('transactions').doc(id).delete();
    } catch(e) {
      throw Exception('Silme gerçekleştirilemedi. $e');
    }
  }
}

// Repository Provider
final transactionRepositoryProvider = Provider<TransactionRepository>((ref) {
  final firestore = ref.watch(firestoreProvider);
  return TransactionRepository(firestore);
});
