// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjWYtNu6Mb1LiQvkKcaDMfX7uSFKNNPH4',
    appId: '1:807569626663:web:198e8aee7b6801026ca002',
    messagingSenderId: '807569626663',
    projectId: 'is-takip-aff20',
    authDomain: 'is-takip-aff20.firebaseapp.com',
    storageBucket: 'is-takip-aff20.firebasestorage.app',
    measurementId: 'G-3FV8TVJWKV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHFTJodLVG4G407c-_Av2wJkxEwVIlCM8',
    appId: '1:807569626663:android:803c0ed230d0917a6ca002',
    messagingSenderId: '807569626663',
    projectId: 'is-takip-aff20',
    storageBucket: 'is-takip-aff20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH9yyVnS4XsVGEguZcS8lYIeY_-G92gic',
    appId: '1:807569626663:ios:6b8f608e1c16a1d86ca002',
    messagingSenderId: '807569626663',
    projectId: 'is-takip-aff20',
    storageBucket: 'is-takip-aff20.firebasestorage.app',
    iosBundleId: 'com.aasoft.isTakip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH9yyVnS4XsVGEguZcS8lYIeY_-G92gic',
    appId: '1:807569626663:ios:9e689b09e81b37796ca002',
    messagingSenderId: '807569626663',
    projectId: 'is-takip-aff20',
    storageBucket: 'is-takip-aff20.firebasestorage.app',
    iosBundleId: 'com.example.isTakip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjWYtNu6Mb1LiQvkKcaDMfX7uSFKNNPH4',
    appId: '1:807569626663:web:e70405101cd39e5f6ca002',
    messagingSenderId: '807569626663',
    projectId: 'is-takip-aff20',
    authDomain: 'is-takip-aff20.firebaseapp.com',
    storageBucket: 'is-takip-aff20.firebasestorage.app',
    measurementId: 'G-GZWEF3R0LK',
  );
}
